# MSA Siham review paper
library(msa)
library(seqinr)

sequences <- c(
"MKLLILTCLVAVALARPKHPINHQGLSPEVLNENLLRFVVAPFPEVFRKENINELSKDIGSESTEDQAMEDAKQMKAGSSSSSEEIVPNSAQQKYIQKEDVPSERYLGYLEQLLRLKKYNVPQLEIVPKSAEEQLHSMKEGNPAHQKQPMIAVNQELAYFYPQLFRQFYQLDAYPSGAWYYLPLGTQYTDAPSFSDIPNPIGSENSGKTTMPLW",#REF
"MKLLILTCLVAVALARPKHPINHQGLSPEVLNENLLRFVVAPFPEVFRKENINELSKDIGSESTEDQAMEDAKQMKAGSSSSSEEIVPNSAQQKYIQKEDVPSERYLGYLEQLLRLKKYNVPQLEIVPKSAEEQLHSMKEGNPAHQKQPMIAVNQELAYFYPQLFRQFYQLDAYPSGAWYYLPLGTQYTDAPSFSDIPNPIGSENSGKTTMPLW",#A
"MKLLILTCLVAVALARPKHPINHQGLSPEVPNENLLRFVVAPFPEVFRKENINELSKDIGSESTEDQAMEDAKQMKAGSSSSSEEIVPNSAQEKYIQKEDVPSERYLGYLEQLLRLKKYNVPQLETVPNSAEEQLHSMKEGNPAHQKQPMIAVNQELAYFYPQLFRQFYQLDAYPSGAWYYLPLGTQYTDAPSFSDIPNPIGSENSGKTTMPLW",#B1
"MKLLILTCLVAVALARPKHPINHQGLSPEVPNENLLRFVVAPFPEVFRKENINELSKDIGSESTEDQAMEDAKQMKAGSSSSSEEIVPNSAQEKYIQKEDVPSERYLGYLEQLLRLKKYNVPQLEIVPKSAEEQLHSMKEGNPAHQKQPMIAVNQELAYFYPQLFRQFYQLDAYPSGAWYYLPLGTQYTDAPSFSDIPNPIGSENSGKTTMPLW",#B2
"MKLLILTCLVAVALARPKHPINHQGLSPEVPNENLLRFVVAPFPEVFRKENINELSKDIGSESTEDQAMEDAKQMKAGSSSSSEEIVPNSAQEKYIQKEDVPSERYLGYLEQLLKLKKYNVPQLEIVPKSAEEQLHSMKEGNPAHQKQPMIAVNQELAYFYPQLFRQFYQLDAYPSGAWYYLPLGTQYTDAPSFSDIPNPIGSENSGKTTMPLW",#B3
"MKLLILTCLVAVALARPKHPINHQGLSPEVPNENLLRFVVAPFPEVFRKENINELSKDIGSESTEDQAMEDAKQMKAGSSSSSEEIVPNSAQEKYIQKEDVPSERYLGYLEQLLKLKKYNVPQLEIVPKSAEEQLHSMKEGNPAHQKQPMIAVNQELAYFYPQLFRQFYQLDAYPSGAWYYLPLGTQYTDAPSFSDIPNPIGSENSGKTAMPLW",#B4
"MKLLILTCLVAVALARPKHPINIQGLSPEVPNENLLRFVVAPFPEVFRKENINELSKDIGSESTEDQAMEDAKQMKAGSSSSSEEIVPNSAQEKYIQKEDVPSERYLGYLEQLLKLKKYNVPQLEIVPKSAEEQLHSMKEGNPAHQKQPMIAVNQELAYFYPQLFRQFYQLDAYPSGAWYYLPLGTQYTDAPSFSDIPNPIGSENSGKTAMPLW",#C
"MKLLILTCLVAVALARPKHPINIQGLSPEVPNENLLRFVVAPFPEVFRKENINELSKDIGSESTEDQAMEDAKQMKAGSSSSSEEIVPNSAQEKYIQKEDVPSERYLGYLEQLLKLKKYNVPQLEIVPKSAEEQLHSMKEGNPAHQKQPMIAVNQELAYFYPQLFRQFYQLDAYPSGAWYYLPLGTQYTDAPSFSDIPNPIGSENSGKTTMPLW",#C1
"MKLLILTCLVAVALARPKHPINHQGLSPEVPNENLLRFVVAPFPEVFRKENINELSKDIGSESTEDQAMEDAKEIVPNSAQEKYIQKEDVPSQERYLGYLEQLLRLKKYNVPQLEIVPKSAEEQLHSMKEGNPAHQKQPMIAVNQELAYFYPQLFRQFYQLDAYPSGAWYYLPLGTQYTDAPSFSDIPNPIGSENSGKTTMPLW"            #D
)


names(sequences) <- c("CSN1S1 REF",
                      "CSN1S1 A",
                      "CSN1S1 B1",
                      "CSN1S1 B2",
                      "CSN1S1 B3",
                      "CSN1S1 B4",
                      "CSN1S1 C",
                      "CSN1S1 C1",
                      "CSN1S1 D")

myAAseqs <- AAStringSet(sequences)
myAlignment <- msa(myAAseqs, "ClustalW")

# Convert the alignment format to seqinr using msaConvert
alignment <- msaConvert(myAlignment, "seqinr::alignment")

# Compute the distance between the alignments
distMatrix <- dist.alignment(alignment, "identity", gap = TRUE)

# Cluster the distance matrix using hclust
clustering <- hclust(distMatrix)
plot(clustering, hang = -1) # Plot the distances
